package modulewise:examples@0.1.0;

world simple-greeter {
  export greet: func(name: string) -> string;
}

world translating-greeter {
  export greet: func(name: string) -> string;
  import translator;
}

world configured-greeter {
  export greet: func(name: string) -> string;
  import translator;
  import wasi:config/store@0.2.0-rc.1;
}

interface translator {
  translate: func(text: string, locale: string) -> string;
}

world simple-translator {
  export translator;
}

world capable-translator {
  export translator;
  import wasi:http/outgoing-handler@0.2.6;
}

world logging-advice {
  export modulewise:interceptor/advice@0.1.0;
  import wasi:logging/logging@0.1.0-draft;
}
