[component.greeter]
uri = "./lib/configured-greeter.wasm"
imports = ["translator"]
config.locale = "fr-FR"

[component.translator]
uri = "./lib/capable-translator.wasm"
imports = ["http-client"]

[capability.http-client]
type = "wasi:http"
