[server.api]
type = "http"
port = 8080

[server.api.route.hello]
path = "/hello"
channel = "names"

[component.greeter]
uri = "./lib/configured-greeter.wasm"
imports = ["translator"]
config.locale = "nl-NL"
subscription = "names"

[component.translator]
uri = "./lib/capable-translator.wasm"
imports = ["http-client"]
interceptors = ["logger"]

[component.logger]
uri = "./lib/logging-advice.wasm"
imports = ["logging-stdout"]

[capability.http-client]
type = "wasi:http"
