[package]
name = "function-factory"
version = "0.2.0"
edition = "2024"
description = "Builds a JSON-based component that targets a function on any other component"
homepage = "https://github.com/modulewise/composable-runtime/tree/main/components/function-factory"
license = "Apache-2.0"
repository = "https://github.com/modulewise/composable-runtime"

[lib]
crate-type = ["cdylib"]

[dependencies]
composable-factory = { git = "https://github.com/modulewise/composable-factory", branch = "main" }
function-adapter = { path = "../../crates/function-adapter" }
wit-bindgen.workspace = true
