[component.guest]
uri = "./lib/guest.wasm"
imports = ["otel"]

[component.otel]
uri = "./lib/otel-to-grpc.wasm"
imports = ["grpc", "wasip2"]

[component.grpc]
uri = "./lib/grpc-to-http.wasm"
imports = ["http"]
config.url = "http://localhost:4317"
config.paths.logs = "/opentelemetry.proto.collector.logs.v1.LogsService/Export"
config.paths.traces = "/opentelemetry.proto.collector.trace.v1.TraceService/Export"

[capability.http]
type = "wasi:http-p2"
h2c-for-grpc = true

[capability.wasip2]
type = "wasi:p2"
