use anyhow::Result;
use std::collections::{HashMap, HashSet};
use std::path::PathBuf;

use super::handlers::{CapabilityConfigHandler, ComponentConfigHandler};
use super::types::{ConfigHandler, DefinitionLoader, GenericDefinition, PropertyMap};
use crate::types::{CapabilityDefinition, ComponentDefinition};

pub struct ConfigProcessor {
    loaders: Vec<Box<dyn DefinitionLoader>>,
    handlers: Vec<Box<dyn ConfigHandler>>,
}

impl ConfigProcessor {
    pub fn new() -> Self {
        Self {
            loaders: Vec::new(),
            handlers: Vec::new(),
        }
    }

    pub fn add_loader(&mut self, loader: Box<dyn DefinitionLoader>) {
        self.loaders.push(loader);
    }

    pub fn add_handler(&mut self, handler: Box<dyn ConfigHandler>) {
        self.handlers.push(handler);
    }

    /// Route paths to loaders via claim, then run the full config pipeline.
    pub fn process(
        mut self,
        paths: &[PathBuf],
    ) -> Result<(Vec<ComponentDefinition>, Vec<CapabilityDefinition>)> {
        // Route paths to loaders
        for path in paths {
            let mut claimed_by = Vec::new();
            for (idx, loader) in self.loaders.iter_mut().enumerate() {
                if loader.claim(path) {
                    claimed_by.push(idx);
                }
            }
            match claimed_by.len() {
                0 => {
                    return Err(anyhow::anyhow!(
                        "No loader can handle path: {}",
                        path.display()
                    ));
                }
                1 => {}
                _ => {
                    return Err(anyhow::anyhow!(
                        "Multiple loaders claimed path: {}",
                        path.display()
                    ));
                }
            }
        }

        // Collect definitions from all loaders
        let mut definitions = Vec::new();
        for loader in &self.loaders {
            definitions.extend(loader.load()?);
        }

        // Build unified handler collection: core handlers + registered handlers
        let mut component_definitions = Vec::new();
        let mut capability_definitions = Vec::new();
        let mut generated_components = Vec::new();
        let mut generated_capabilities = Vec::new();
        {
            let mut all_handlers: Vec<Box<dyn ConfigHandler + '_>> = Vec::new();
            all_handlers.push(Box::new(ComponentConfigHandler::new(
                &mut component_definitions,
            )));
            all_handlers.push(Box::new(CapabilityConfigHandler::new(
                &mut capability_definitions,
            )));
            all_handlers.extend(self.handlers);

            dispatch(&mut definitions, &mut all_handlers)?;

            // Collect definitions generated by custom handlers
            for handler in &mut all_handlers {
                generated_components.extend(handler.generated_component_definitions());
                generated_capabilities.extend(handler.generated_capability_definitions());
            }
        }
        component_definitions.extend(generated_components);
        capability_definitions.extend(generated_capabilities);

        // Resolve placeholders
        resolve_placeholders_in_components(&mut component_definitions)?;
        resolve_placeholders_in_capabilities(&mut capability_definitions)?;

        // Cross-definition validation
        validate_scopes(&component_definitions, &capability_definitions)?;
        validate_names(&component_definitions, &capability_definitions)?;
        validate_imports(&component_definitions, &capability_definitions)?;

        Ok((component_definitions, capability_definitions))
    }
}

use super::types::CategoryClaim;

// A category claim registered by a handler, with its handler index.
struct RegisteredClaim {
    handler_idx: usize,
    claim: CategoryClaim,
}

fn dispatch(
    definitions: &mut Vec<GenericDefinition>,
    handlers: &mut [Box<dyn ConfigHandler + '_>],
) -> Result<()> {
    // Build category => list of claims (handler index + optional selector).
    // Validate: if any claim on a category has no selector, it must be the only claim.
    let mut category_claims: HashMap<String, Vec<RegisteredClaim>> = HashMap::new();
    for (idx, handler) in handlers.iter().enumerate() {
        for claim in handler.claimed_categories() {
            category_claims
                .entry(claim.category.to_string())
                .or_default()
                .push(RegisteredClaim {
                    handler_idx: idx,
                    claim,
                });
        }
    }
    for (category, claims) in &category_claims {
        if claims.len() > 1 {
            let has_unselected = claims.iter().any(|c| c.claim.selector.is_none());
            if has_unselected {
                return Err(anyhow::anyhow!(
                    "Category '{category}' claimed exclusively (without a selector) and by other handlers"
                ));
            }
        }
    }

    // Build claimed properties map: (category, property) => handler index
    let mut property_claims: HashMap<(String, String), usize> = HashMap::new();
    for (idx, handler) in handlers.iter().enumerate() {
        for (category, properties) in handler.claimed_properties() {
            for prop in properties {
                let key = (category.to_string(), prop.to_string());
                if let Some(&existing_idx) = property_claims.get(&key)
                    && existing_idx != idx
                {
                    return Err(anyhow::anyhow!(
                        "Property '{prop}' on category '{category}' claimed by multiple handlers"
                    ));
                }
                property_claims.insert(key, idx);
            }
        }
    }

    for def in definitions.drain(..) {
        let claims = category_claims.get(&def.category).ok_or_else(|| {
            anyhow::anyhow!(
                "Unknown category '{}'. Known categories: {:?}",
                def.category,
                category_claims.keys().collect::<Vec<_>>()
            )
        })?;

        let owner_idx = resolve_owner(claims, &def)?;

        let (core_properties, claimed_by_handler) =
            split_properties(def.properties, &def.category, owner_idx, &property_claims);

        handlers[owner_idx].handle_category(&def.category, &def.name, core_properties)?;

        for (handler_idx, properties) in claimed_by_handler {
            handlers[handler_idx].handle_properties(&def.category, &def.name, properties)?;
        }
    }

    Ok(())
}

// Find the single handler that owns a definition.
// Returns an error if not exactly one match.
fn resolve_owner(claims: &[RegisteredClaim], def: &GenericDefinition) -> Result<usize> {
    // Single claim with no selector => unconditional category owner
    if claims.len() == 1 && claims[0].claim.selector.is_none() {
        return Ok(claims[0].handler_idx);
    }

    // Flatten properties to string-to-string for selector matching
    let flat = flatten_for_selector(&def.properties);

    let mut matched = Vec::new();
    for rc in claims {
        let matches = rc.claim.selector.as_ref().is_none_or(|s| s.matches(&flat));
        if matches {
            matched.push(rc.handler_idx);
        }
    }

    match matched.len() {
        0 => Err(anyhow::anyhow!(
            "No handler matched definition '{}' in category '{}'",
            def.name,
            def.category
        )),
        1 => Ok(matched[0]),
        _ => Err(anyhow::anyhow!(
            "Multiple handlers matched definition '{}' in category '{}'",
            def.name,
            def.category
        )),
    }
}

// Flatten a PropertyMap for selector matching. Scalar values become
// Some(string), arrays and null become None (key present but no scalar value).
// Nested objects use dot-delimited keys.
fn flatten_for_selector(properties: &PropertyMap) -> HashMap<String, Option<String>> {
    let mut result = HashMap::new();
    flatten_recursive(properties, "", &mut result);
    result
}

fn flatten_recursive(
    map: &PropertyMap,
    prefix: &str,
    result: &mut HashMap<String, Option<String>>,
) {
    for (key, value) in map {
        let full_key = if prefix.is_empty() {
            key.clone()
        } else {
            format!("{prefix}.{key}")
        };
        match value {
            serde_json::Value::String(s) => {
                result.insert(full_key, Some(s.clone()));
            }
            serde_json::Value::Bool(b) => {
                result.insert(full_key, Some(b.to_string()));
            }
            serde_json::Value::Number(n) => {
                result.insert(full_key, Some(n.to_string()));
            }
            serde_json::Value::Object(obj) => {
                let nested: PropertyMap = obj.iter().map(|(k, v)| (k.clone(), v.clone())).collect();
                flatten_recursive(&nested, &full_key, result);
            }
            serde_json::Value::Array(_) | serde_json::Value::Null => {
                result.insert(full_key, None);
            }
        }
    }
}

fn split_properties(
    mut properties: PropertyMap,
    category: &str,
    owner_idx: usize,
    property_claims: &HashMap<(String, String), usize>,
) -> (PropertyMap, HashMap<usize, PropertyMap>) {
    let mut claimed: HashMap<usize, PropertyMap> = HashMap::new();

    let keys: Vec<String> = properties.keys().cloned().collect();
    for key in keys {
        let lookup = (category.to_string(), key.clone());
        if let Some(&handler_idx) = property_claims.get(&lookup)
            && handler_idx != owner_idx
            && let Some(value) = properties.remove(&key)
        {
            claimed.entry(handler_idx).or_default().insert(key, value);
        }
    }

    (properties, claimed)
}

// --- Placeholder resolvers ---

fn resolve_placeholders_in_components(definitions: &mut [ComponentDefinition]) -> Result<()> {
    for def in definitions {
        resolve_placeholders_in_map(&mut def.config)?;
    }
    Ok(())
}

fn resolve_placeholders_in_capabilities(definitions: &mut [CapabilityDefinition]) -> Result<()> {
    for def in definitions {
        resolve_placeholders_in_map(&mut def.properties)?;
    }
    Ok(())
}

fn resolve_placeholders_in_map(map: &mut HashMap<String, serde_json::Value>) -> Result<()> {
    for value in map.values_mut() {
        resolve_placeholders_in_value(value)?;
    }
    Ok(())
}

fn resolve_placeholders_in_value(value: &mut serde_json::Value) -> Result<()> {
    match value {
        serde_json::Value::String(s) => {
            if let Some(resolved) = resolve_placeholder(s)? {
                *s = resolved;
            }
        }
        serde_json::Value::Array(arr) => {
            for item in arr {
                resolve_placeholders_in_value(item)?;
            }
        }
        serde_json::Value::Object(map) => {
            for v in map.values_mut() {
                resolve_placeholders_in_value(v)?;
            }
        }
        _ => {}
    }
    Ok(())
}

fn resolve_placeholder(s: &str) -> Result<Option<String>> {
    if !s.starts_with("${") || !s.ends_with('}') {
        return Ok(None);
    }

    let inner = &s[2..s.len() - 1];
    if let Some(env_expr) = inner.strip_prefix("process:env:") {
        let (env_key, default) = match env_expr.split_once('|') {
            Some((key, default)) => (key, Some(default)),
            None => (env_expr, None),
        };
        match (std::env::var(env_key), default) {
            (Ok(value), _) => Ok(Some(value)),
            (Err(_), Some(default)) => Ok(Some(default.to_string())),
            (Err(_), None) => Err(anyhow::anyhow!(
                "Environment variable '{env_key}' not set (referenced in config placeholder '{s}')"
            )),
        }
    } else {
        Err(anyhow::anyhow!("Unknown placeholder pattern: '{s}'"))
    }
}

// --- Cross-definition validation ---

// TODO: replace with label selector validation
fn validate_scopes(
    components: &[ComponentDefinition],
    capabilities: &[CapabilityDefinition],
) -> Result<()> {
    for def in capabilities {
        match def.scope.as_str() {
            "any" => {}
            "package" | "namespace" => {
                return Err(anyhow::anyhow!(
                    "Capability '{}' cannot use scope='{}' - only components support package/namespace scoping",
                    def.name,
                    def.scope
                ));
            }
            _ => {
                return Err(anyhow::anyhow!(
                    "Invalid scope: '{}'. Must be: any",
                    def.scope
                ));
            }
        }
    }
    for def in components {
        match def.scope.as_str() {
            "any" | "package" | "namespace" => {}
            _ => {
                return Err(anyhow::anyhow!(
                    "Invalid scope: '{}'. Must be one of: any, package, namespace",
                    def.scope
                ));
            }
        }
    }
    Ok(())
}

fn validate_names(
    components: &[ComponentDefinition],
    capabilities: &[CapabilityDefinition],
) -> Result<()> {
    let mut all_names = HashSet::new();
    for def in capabilities {
        validate_name_chars(&def.name)?;
        if !all_names.insert(&def.name) {
            return Err(anyhow::anyhow!("Duplicate definition name: '{}'", def.name));
        }
    }
    for def in components {
        validate_name_chars(&def.name)?;
        if !all_names.insert(&def.name) {
            return Err(anyhow::anyhow!("Duplicate definition name: '{}'", def.name));
        }
    }
    Ok(())
}

fn validate_name_chars(name: &str) -> Result<()> {
    if name.starts_with('_') || name.contains('$') {
        return Err(anyhow::anyhow!(
            "Definition name '{name}' is invalid: names cannot start with '_' or contain '$' (reserved for internal use)"
        ));
    }
    Ok(())
}

fn validate_imports(
    components: &[ComponentDefinition],
    capabilities: &[CapabilityDefinition],
) -> Result<()> {
    let all_names: HashSet<&str> = components
        .iter()
        .map(|d| d.name.as_str())
        .chain(capabilities.iter().map(|d| d.name.as_str()))
        .collect();

    for def in components {
        for import_name in &def.imports {
            validate_name_chars(import_name)
                .map_err(|e| anyhow::anyhow!("Invalid import for '{}': {e}", def.name))?;
            if !all_names.contains(import_name.as_str()) {
                return Err(anyhow::anyhow!(
                    "Component '{}' imports undefined definition '{}'",
                    def.name,
                    import_name
                ));
            }
        }
    }
    Ok(())
}
