[component.greeter]
uri = "./target/wasm32-unknown-unknown/release/greeter.wasm"
interceptors = ["logging-advice"]

[component.logging-advice]
uri = "./target/wasm32-unknown-unknown/release/logger.wasm"
imports = ["stdout-logger"]

[component.stdout-logger]
uri = "./wasi-logging-to-stdout.wasm"
# could use this instead of pulling in the build script:
# uri = "oci://ghcr.io/componentized/logging/to-stdout:v0.2.1"
imports = ["stdio", "wasip2"]

[capability.stdio]
type = "wasi:cli"
inherit-stdio = true

[capability.wasip2]
type = "wasi:p2"
