[server.api]
type = "http"
port = 8888

[server.api.route.hello]
path = "/hello/{name}"
component = "hello"
function = "greet"

[server.api.route.bonjour]
path = "/bonjour"
channel = "names"

[component.hello]
uri = "../hello-world/greeter/target/wasm32-unknown-unknown/release/greeter.wasm"

[component.bonjour]
uri = "../hello-world/greeter/target/wasm32-unknown-unknown/release/greeter.wasm"
config.greeting = "Bonjour"
subscription = "names"
