[server.api]
type = "http"
port = 8888

[server.api.route.hello]
method = "GET"
path = "/hello/{name}"
component = "hello"
function = "greet"

[server.api.route.bonjour]
method = "POST"
path = "/bonjour"
content-type = "text/plain"
channel = "names"
reply-timeout-ms = 1000

[component.hello]
uri = "../hello-world/greeter/target/wasm32-unknown-unknown/release/greeter.wasm"

[component.bonjour]
uri = "../hello-world/greeter/target/wasm32-unknown-unknown/release/greeter.wasm"
config.greeting = "Bonjour"

[subscription.names]
component = "bonjour"
