[component.guest]
uri = "./target/wasm32-unknown-unknown/release/guest.wasm"
imports = ["otel"]

[component.otel]
uri = "./target/wasm32-wasip2/release/otel_to_grpc.wasm"
imports = ["grpc", "wasip2"]

[component.grpc]
uri = "./target/wasm32-unknown-unknown/release/grpc_to_http.wasm"
imports = ["http", "io"]
config.url = "http://localhost:4317"
config.paths.logs = "/opentelemetry.proto.collector.logs.v1.LogsService/Export"
config.paths.traces = "/opentelemetry.proto.collector.trace.v1.TraceService/Export"

[capability.http]
type = "wasi:http"

[capability.io]
type = "wasi:io"

[capability.wasip2]
type = "wasi:p2"
