[component.guest]
uri = "./target/wasm32-unknown-unknown/release/guest.wasm"
imports = ["otel"]

[component.otel]
uri = "./target/wasm32-wasip2/release/otel_to_grpc.wasm"
imports = ["grpc", "wasip2"]

[capability.grpc]
type = "grpc"
url = "http://localhost:4317"
paths.logs = "/opentelemetry.proto.collector.logs.v1.LogsService/Export"
paths.traces = "/opentelemetry.proto.collector.trace.v1.TraceService/Export"

[capability.wasip2]
type = "wasi:p2"
